### ISSUE TITLE
Create a code review checklist.

### ISSUE THREAD

**Issue by jaffee** [pilosa/general#20]
E.G.

- [ ] Are external docs updated?
- [ ] Do minor/major versions need to be changed? (compatibility)
- [ ] is code commented?
- [ ] have tests been written. Do they cover the new functionality?

What else?

I believe we can make a template for code review that automatically pre-populate similar to the way issues do.

**Comment by jaffee** [comment]
I think we can implement this as part of the pull request template - we don't have one right now, but it should remind those submitting a pull request to add relevant details and link to a ticket. At the bottom it can have the code review checklist to remind reviewers what they need to do.

**Comment by travisturner** [comment]
good idea @jaffee. I'll take a pass at a pull request template and submit it for feedback.
